import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>School Data</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<h1 className={styles.heading}>School</h1>

				<div className={styles.allLinks}>
					<Link href={"/admin/login"}>
						<div className="p-2 bg-slate-50 w-[max-content] rounded-xl text-slate-950">
							Admin Login
						</div>
					</Link>
					<Link href={"/students"}>
						<div className={styles.linkTab}>All students</div>
					</Link>
					<Link href={"/teachers"}>
						<div className={styles.linkTab}>All teachers</div>
					</Link>
					<Link href={"/approuter/students"}>
						<div className={styles.linkTab}>All students w/ App Router</div>
					</Link>
					<Link href={"/approuter/teachers"}>
						<div className={styles.linkTab}>All teachers w/ App Router</div>
					</Link>
					<Link href={"/approuter/students-with-long-load"}>
						<div className={styles.linkTab}>
							All students w/ App Router (Long Loading)
						</div>
					</Link>
				</div>
			</main>
		</>
	);
}
